InsecureWebApp/Models/Prescription.cs
namespace MicroFocus.InsecureWebApp.Models
{
    public class Prescription
    {
        public int ID { get; set; }
        public string DocName { get; set; }
        public string Advice { get; set; }
        public string Product { get; set; }
        public string UserId { get; set; }
    }
}

InsecureWebApp/Controllers/PrescriptionController.cs
using MicroFocus.InsecureWebApp.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;

namespace MicroFocus.InsecureWebApp.Controllers
{
    [Route("api/v1/[controller]")]
    [ApiController]
    public class PrescriptionController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private const string PRESCRIPTION_LOCATION = "Files\\Prescriptions\\";

        public PrescriptionController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public ContentResult GetSearchText(string sSearchText)
        {

            return Content("Prescription Search By : " + sSearchText, "text/html");
        }

        [HttpGet("GetPrescription")]
        public List<Models.Prescription> GetPrescription(string sSearchText)
        {
            List<Models.Prescription> pres;
            if (string.IsNullOrEmpty(sSearchText))
            {
                pres = _context.Prescription.ToList();
            }
            else
            {
                pres = _context.Prescription.Where(m => m.DocName.Contains(sSearchText)).ToList();
            }
            return pres; //Ok(pres);
        }


        [HttpGet("GetDoctorName")]
        public Models.Prescription GetDoctorNameByPresId(int iPresId)
        {
            var pres = _context.Prescription.Where(m => m.ID.Equals(iPresId)).FirstOrDefault();
            return pres;
        }

        [HttpPost("UploadXml")]
        public IActionResult UploadXml(string sPath)
        {
            XmlDocument xdoc = new XmlDocument();
            xdoc.XmlResolver = new XmlUrlResolver();
            xdoc.LoadXml(sPath);

            return Content(xdoc.InnerText);
        }

        [HttpPost("UploadFile")]
        public async Task<bool> UploadFile(IFormFile file, string sPath)
        {
            bool blnResult = false;
            try
            {
                using (var stream = new FileStream(sPath, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                blnResult = true;
            }catch (Exception ex)
            {
                throw new FileLoadException(ex.Message);
            }
            return blnResult;
        }

        [HttpPost("UpdateXml")]
        public async Task<bool> UpdateXml(string sFileName, string xmlContent)
        {
            bool retFunc = false;
            if (!string.IsNullOrEmpty(xmlContent))
            {
                await Task.Delay(100);
                string path = Path.Combine(Directory.GetCurrentDirectory(), "Files"+ Path.DirectorySeparatorChar +"Prescriptions" + Path.DirectorySeparatorChar) + sFileName;

                XmlDocument document = new XmlDocument();
                document.Load(path);

                document.InnerXml = xmlContent;
                document.Save(path);
                retFunc = true;
            }
            return retFunc;
        }

        [HttpGet("DownloadFile")]
        public FileResult DownloadFile(string fileName)
        {
            //Build the File Path.
            string path = Path.Combine(Directory.GetCurrentDirectory(), "Files"+ Path.DirectorySeparatorChar +"Prescriptions" + Path.DirectorySeparatorChar) + fileName;

            //Read the File data into Byte Array.
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the File to Download.
            return File(bytes, "application/octet-stream", fileName);
        }

    }
}

InsecureWebApp/Pages/Prescription/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using MicroFocus.InsecureWebApp.Models;
using MicroFocus.InsecureWebApp.Controllers;
using System.Linq;
using Microsoft.AspNetCore.Http;
using System.Net;
using System;
using System.Text;

namespace MicroFocus.InsecureWebApp.Pages.Prescription
{
    public class PresModel : PageModel
    {
        private readonly Data.ApplicationDbContext _context;
        public List<MicroFocus.InsecureWebApp.Models.Prescription> Prescriptions { get; set; }
        public Controllers.PrescriptionController pc;

        [BindProperty(SupportsGet = true)]
        public string Search { get; set; }

        public PresModel(MicroFocus.InsecureWebApp.Data.ApplicationDbContext context)
        {
            _context = context;
            pc = new PrescriptionController(_context);
        }

        public async Task OnGet()
        {
            await Task.Delay(1);
            List<Models.Prescription> p = pc.GetPrescription(Search);
            //Search = pc.GetSearchText(Search);
            Prescriptions = p;
        }

        public string GetSearchText()
        {
            ContentResult cr = pc.GetSearchText(Search);
            ViewData.Add("XSS", cr.Content);
            return cr.Content.ToString();
        }

        public IActionResult OnGetDoctorName(string ID, string Msg)
        {
            int iPresId;
            int.TryParse(ID, out iPresId);
            Models.Prescription pres = pc.GetDoctorNameByPresId(iPresId);
            var result = new ObjectResult(pres.DocName + " " + Msg + " " + ID)
            {
                StatusCode = (int)HttpStatusCode.OK
            };

            return result;
        }
    }
}

InsecureWebApp/Pages/Prescription/Upload.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;
using System.Threading.Tasks;
using MicroFocus.InsecureWebApp.Models;
using System.Collections.Generic;
using System.Xml;

namespace MicroFocus.InsecureWebApp.Pages.Prescription
{
    public class UploadModel : PageModel
    {
        private readonly Data.ApplicationDbContext _context;
        public Controllers.PrescriptionController pc;
        public List<PrescriptionFileModel> files { get; set; }

        public UploadModel(MicroFocus.InsecureWebApp.Data.ApplicationDbContext context)
        {
            _context = context;
            pc = new Controllers.PrescriptionController(_context);
        }

        public void OnGet()
        {
            //Copy File names to Model collection.
            this.files = new List<PrescriptionFileModel>();
            try
            {
                //Fetch all files in the Folder (Directory).
                string[] filePaths = Directory.GetFiles(Path.Combine(Directory.GetCurrentDirectory(), "Files"+ Path.DirectorySeparatorChar +"Prescriptions"), "*.xml");


                foreach (string filePath in filePaths)
                {
                    //string fullPath = filePath + "\\" + Path.GetFileName(filePath);
                    files.Add(new PrescriptionFileModel { FileName = Path.GetFileName(filePath), FileDesc = getXmlFileContent(filePath), xml = getXml(filePath) });
                }
            }
            catch (System.Exception ex)
            { }
        }

        public string getXml(string sFilePath)
        {
            string xmlFileContent = string.Empty;
            XmlReaderSettings settings = new XmlReaderSettings();
            //settings.ProhibitDtd = false;
            
            settings.DtdProcessing = DtdProcessing.Parse;
            settings.IgnoreWhitespace = true;
            settings.IgnoreComments = true;
            settings.XmlResolver = new XmlUrlResolver();
            //Method 2
            XmlDocument document = new XmlDocument();
            document.XmlResolver = new XmlUrlResolver();
            document.Load(sFilePath);
            using (var fileStream = System.IO.File.OpenText(sFilePath))
            using (XmlReader reader = XmlReader.Create(sFilePath,settings))
            {
                while (reader.Read())
                {
                    string result = reader.NodeType switch
                    {
                        XmlNodeType.Element when reader.Name == "product" => $"{reader.Name}\n",
                        XmlNodeType.Element => $"{reader.Name}: ",
                        XmlNodeType.Text => $"{reader.Value}\n",
                        XmlNodeType.EndElement when reader.Name == "product" => "-------------------\n",
                        _ => ""
                    };
                    xmlFileContent += result;

                }
            }
            return xmlFileContent;
            //return document.InnerText;
        }

        public string getXmlFileContent(string sFilePath)
        {
            string xmlFileContent = string.Empty;
            XmlReaderSettings settings = new XmlReaderSettings();
            settings.ProhibitDtd = false;
            settings.IgnoreWhitespace = true;
            settings.IgnoreComments = true;
            //settings.XmlResolver =  = null;

            //Method 1
            XmlDocument document = new XmlDocument();
            document.Load(sFilePath);
            XmlNamespaceManager m = new XmlNamespaceManager(document.NameTable);
            using (StreamReader fileStream = System.IO.File.OpenText(sFilePath))
            using (XmlReader reader = XmlReader.Create(fileStream, settings))
            {
                while (reader.Read())
                {
                    string result = reader.NodeType switch
                    {
                        XmlNodeType.Element when reader.Name == "product" => $"{reader.Name}\n",
                        XmlNodeType.Element => $"{reader.Name}: ",
                        XmlNodeType.Text => $"{reader.Value}\n",
                        XmlNodeType.EndElement when reader.Name == "product" => "-------------------\n",
                        _ => ""
                    };
                    xmlFileContent += result;
                }
            }
            //return xmlFileContent; 
            return document.InnerXml.ToString();

            
        }

        //public FileResult DownloadFile(string fileName)
        //{
        //    //Build the File Path.
        //    string path = Path.Combine(Directory.GetCurrentDirectory(), "Files\\Prescriptions") + fileName;

        //    //Read the File data into Byte Array.
        //    byte[] bytes = System.IO.File.ReadAllBytes(path);

        //    //Send the File to Download.
        //    return File(bytes, "application/octet-stream", fileName);
        //}

        public async Task<IActionResult> OnPost(IFormFile PresFile)
        {
            if (PresFile == null || PresFile.Length == 0)
                return Content("file not selected");

            var path = Path.Combine(Directory.GetCurrentDirectory(), "Files"+ Path.DirectorySeparatorChar +"Prescriptions", PresFile.FileName);
            var task = await pc.UploadFile(PresFile, path);
            
            if (!task)
            {
                throw new FileLoadException();
            }
            TempData["FileUpload"] = "File Uploaded Successfully";
            return RedirectToPage("Upload");
        }

        public async Task<IActionResult> OnPostUpdateXML(string sFileName, string xmlContent)
        {
            if (!string.IsNullOrEmpty(xmlContent))
            {
                var task = await pc.UpdateXml(sFileName, xmlContent);

                if (!task)
                {
                    throw new FileLoadException();
                }
            }
            return RedirectToPage("Upload");
        }
    }
}

InsecureWebApp/Pages/Prescriptions.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MicroFocus.InsecureWebApp.Pages
{
    public class PrescriptionsModel : PageModel
    {
        private readonly ILogger<PrescriptionsModel> _logger;

        public PrescriptionsModel(ILogger<PrescriptionsModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

InsecureWebApp/Pages/Prescription/Index.cshtml
@page "{Search?}"
@using MicroFocus.InsecureWebApp.Models
@using Microsoft.AspNetCore.Mvc.Controllers
@using System.Text

@model  MicroFocus.InsecureWebApp.Pages.Prescription.PresModel

@{

    ViewData["Title"] = "Index";
}
<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0"><a asp-page="/Prescriptions">List</a> </div>
        </div>
    </div>
</div>



<div class="site-section-sm">

    <div class="container">
        @{
            string search = Request.Query["Search"];
            if (!string.IsNullOrEmpty(search))
            {
                <div class="row pt-2">
                    <div class="col-md-12 text-center">
                        <h2>Search</h2>
                        <h5><span class="bg-light text-dark">
                        @{
                            var str = Model.GetSearchText().ToString();
                         }
                            @Html.Raw(ViewData["XSS"].ToString())
                            <!--@Html.Raw(Request.Query["Search"])-->
                        </span></h5>
                    </div>
                </div>
            }
        }

        <div class="row mb-1">
            <form asp-action="/Prescription" class="col-md-12" method="GET">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search prescription" name="Search" id="Search" value="@Html.Raw(Model.Search)">
                    <input type="text" hidden class="form-control" name="Msg" id="Msg" value="<b>wrote this prescription Number</b>">
                    <div class="input-group-append">
                        <button class="btn btn-secondary" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
            @foreach (var item in Model.Prescriptions)
            {
                <div class="row pt-1 border border-info">
                    <div class="col">
                        <button class="btnGetDoc btn btn-primary" data-pres-id="@item.ID" type="button" id="btnGetDoc_@item.ID">Get Prescription</button>
                    </div>
                    <div class="col">
                        <h3 class="text-dark"><a asp-page="./Details" asp-route-id="@item.ID">@item.ID</a></h3>
                    </div>
                    <div class="col">
                        <span class="text-info" id="Add_Update_Details_@item.ID">
                        @item.DocName
                        </span>
                    </div>
                    <div class="col">
                        <p class="text-info">
                            @Html.DivInjectionHTMLString(item.Advice)
                        </p>
                    </div>
                </div>
            }
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        (function ($) {
            $(document).ready(function () {
                $(".btnGetDoc").on('click', function(event){
                    event.stopPropagation();
                    event.stopImmediatePropagation();
                    var PresId = $(this).data("pres-id");
                    const uri = '/prescription?Handler=DoctorName&ID='+PresId;
                    var sMsg = $("#Msg").val(); //"<b>wrote this prescription Number</b>";
                    var spanId = "#Add_Update_Details_" + PresId

                    $.ajax({
                        type: 'GET',
                        url: '/prescription?Handler=DoctorName',
                        data: { ID: PresId, Msg: sMsg },
                        success: function(data, textStatus, xhr) {
                                //alert(xhr.responseText);
                                //alert(spanId);
                                $(spanId).html(xhr.responseText);
                        },
                        error: function (jqXHR, status, err) {//status is Error and the errorThrown is undefined
                            //alert(jqXHR.responseText);
                            alert('Request Status : ' + jqXHR.status + ' has issued a status text of  : ' + jqXHR.statusText);
                            //$("#Add_Update_Details").html(jqXHR.responseText);
                        }
                    });
                });

            });
        })(jQuery);
    </script>
}

InsecureWebApp/Pages/Prescription/Upload.cshtml
@page
@using MicroFocus.InsecureWebApp.Models
@using Microsoft.AspNetCore.Mvc.Controllers
@using System.Text
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model MicroFocus.InsecureWebApp.Pages.Prescription.UploadModel

@{

    ViewData["Title"] = "Upload Prescription";
}
<style>
.image-upload {
    width: 100%;
    height: 300px;
    border: 1px dashed #ddd;
    border-radius: 5px;
    margin-bottom: 20px;
    position: relative;
    text-align: center;
    background: #f8f8f9;
    color: #666;
    overflow: hidden;
}


.item-wrapper form img {
    margin-bottom: 20px;
    width: auto;
    height: auto;
    max-height: 400px;
    width: auto;
    border-radius: 5px;
    overflow: hidden;
}


.image-upload img {
    height: 100%!important;
    width: auto!important;
    border-radius: 0px;
    margin: 0 auto;
}

.image-upload i {
    font-size: 6em;
    color: #ccc;
}


.image-upload input {
    cursor: pointer;
    opacity: 0;
    height: 100%;
    width: 100%;
    z-index: 10;
    position: absolute;
    top: 0;
    left: 0;
}
</style>
<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0"><a asp-page="/Prescriptions">List</a> </div>
        </div>
    </div>
</div>
<div class="site-section-sm">

    <div class="container">

       @{
           if (TempData["FileUpload"] != null){
                string result = TempData["FileUpload"].ToString();
                if (!string.IsNullOrEmpty(result))
                {
                    <div class="row pt-2">
                        <div class="col-md-12 text-center">
                            <h2>@Html.Raw(result)</h2>
                        </div>
                    </div>
                }
           }
        }

        <div class="row mb-1">
            <div class="col-md-12 text-center">
            <form id=frmUpload name=frmUpload asp-controller="PrescriptionController" asp-action="UploadFile" method="post" enctype="multipart/form-data">  
                <div class="image-upload">
                    <label style="cursor: pointer;" for="file_upload">
                        <img src="" alt="" class="uploaded-image">
                        <div class="h-100">
                                <div class="dplay-tbl">
                                <div class="dplay-tbl-cell">
                                    <i class="fa fa-upload" aria-hidden="true"></i>
                                    <h5><b>Choose Your XML to Upload</b></h5>
                                    <h6 class="mt-10 mb-70">Or Drop Your XML Here</h6>
                                </div>
                            </div>
                        </div><!--upload-content-->
                        <input data-required="image" placeholder="Upload prescription XML" type="file" name="PresFile" id="PresFile" class="image-input" data-traget-resolution="image_resolution" accept=".xml">
                    </label>
                 </div>

                <div class="row pt-1 border border-info">
                     <div class=col>
                         File Name
                     </div>
                     <div class=col>
                         File Content
                     </div>
                     <div class=col>
                         Processed xml
                     </div>
                     <div class=col>
                         Download
                     </div>
                 </div>
           @foreach (PrescriptionFileModel file in Model.files)
            {
                <div class="row pt-1 border border-info">
                    <div class="col">
                        @file.FileName
                    </div>
                    <div class="col text-wrap" style="height:130px; width:300px;">
                        <form id="frmXmlUpd" name="frmXmlUpd" method="post"> 
                            <input asp-for="@file.FileName" class="form-control" name="sFileName" id="sFileName" type="hidden">
                            <textarea class="form-control" name="xmlContent" id="xmlContent" rows="3" style="resize:none">@Html.Raw(file.FileDesc)</textarea>
                            <div class="input-group-addon input-group-append">
                                <button class="btn btn-secondary" asp-page-handler="UpdateXml" type="submit">
                                    <i class="fa fa-save"></i>
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="col">
                        @Html.Raw(file.xml)
                    </div>
                    <div class="col">
                        <a asp-controller="Prescription" asp-action="DownloadFile" asp-route-filename="@file.FileName">Downlaod</a>
                    </div>
                </div>
            }                
                
@*                <input type="file" class="form-control" placeholder="Upload prescription XML" name="PresFile" id="PresFile" accept=".xml">
                    <div class="input-group-append">
                        <button class="btn btn-secondary" type="submit">
                            <i class="fa fa-upload"></i>
                        </button>
                    </div>*@
            </form>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        (function ($) {
            $(document).ready(function () {
                document.getElementById("PresFile").onchange = function() {
                    document.getElementById("frmUpload").submit();
                };
            });
        })(jQuery);
    </script>
}